id: P77084E24
initial_creation_type: ocr
source_metadata:
  volumes:
    4a16063154c64e88818400bbc431af66:
      base_file: v016.txt
      image_group_id: I1PD95861
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པའི་དགོངས་པ་རབ་གསལ་ཞེས་བྱ་བ་བཤད་པའི་ཊཱི་ཀཱ།
      total_pages: 1354
      volume_number: 16
